apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-class-test
  namespace: broker-online
  labels:
    app: provider-test-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-test-secret
  template:
    metadata:
      labels:
        app: provider-test-secret
    spec:
      serviceAccountName: broker-online-secrets
      containers:
        - name: provider-test-container
          image: google/cloud-sdk:alpine
          command: ["sleep", "infinity"] # Keeps the container running
          volumeMounts:
            - mountPath: "/var/secrets"
              name: secret-volume
      volumes:
        - name: secret-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "certi-secret-provider"
