#This file bounds the secret in secret-manager with 
#the secret provider class

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: certi-secret-provider
  namespace: broker-online
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/<project>/secrets/<secrets_name/versions/1"
        path: "certi-secret.txt"

